### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Jimmyf3** [codemasher/gw2-database#5]
Hi

First of all, sorry for my bad english.

So, i would like to install on my computer this gw2-database. I'm using EasyPHP with PHP 5.6.19 & MySQL 5.7.11.
I couldn't find a tutorial to properly install gw2-database, so i tried a few things : 
I have uploaded the 5 SQL files on phpMyAdmin, edit the file .env_example like this :

```
DB_MYSQLI_HOST=localhost
DB_MYSQLI_PORT=
DB_MYSQLI_SOCKET=
DB_MYSQLI_DATABASE=gw2wiki
DB_MYSQLI_USERNAME=root
DB_MYSQLI_PASSWORD=
DB_MYSQLI_SSL_CA=
DB_MYSQLI_SSL_CAPATH=
DB_MYSQLI_SSL_CERT=
DB_MYSQLI_SSL_CIPHER=
DB_MYSQLI_SSL_KEY=
```

but without results. I'm lost, i don't know what to do...

So, if someone have a tutorial, or can take a few minutes to explain, I would appreciate it

**Comment by codemasher** [comment]
Hey,

thank you for the report and sorry for missing out! I'm already way too much in the PhpStorm workflow that i don't care much about these details... :D

It's actually pretty simple.
- first, get composer from https://getcomposer.org/download/ , scroll down, get the latest .phar archive
- put the `composer.phar` into your php directory and make sure this directory has global access. I have a .bat file for Windows, which looks like `@%PHP_DIR%\php.exe "%~dp0composer.phar" %*` where `PHP_DIR` is a global system variable.
- git clone this repository (downloading and extracting the .zip is pretty much the same)
- go to the project root folder which contains the `composer.json`
- run `php composer.phar install` and check if all libraries were downloaded correctly
- run `php ./cli/updater.php`

That's it. (or should be...)
If not, feel free to poke me over here: https://gitter.im/chillerlan/gw2hero.es

https://packagist.org/packages/chillerlan/gw2-database
