### ISSUE TITLE
Installation on Hosting Site

### ISSUE THREAD

**Issue by Eranio2012** [codemasher/gw2-database#6]
Hello i have a normal Webhosting with mysql db.

have you installation Instructions for me wenn i load this git up to my domain say me 
"Fatal error: Interface 'chillerlan\GW2DB\Helpers\Maps\MapdataInterface' not found in"
and more errors.

Install instructions was i need was nice Thanks

**Comment by codemasher** [comment]
Hmm, that sounds like an incorrect path problem. Mind to post a dump of the error output?

**Comment by Eranio2012** [comment]
is direct from github 
i have only edit the dbconfig

**Comment by codemasher** [comment]
That doesn't answer my question, though. Can you please post the output or point me to the webspace where you installed it?

**Comment by Eranio2012** [comment]
Fatal error: Class 'chillerlan\GW2DB\Updaters\UpdaterAbstract' not found in /home/u281093527/public_html/test/src/Updaters/Items/UpdateItemDB.php on line 17
Link
http://xxxxxxxxx/test/src/Updaters/Items/UpdateItemDB.php

**Comment by codemasher** [comment]
Do you want me to help you or do you want to waste my time? I know where the error is thrown. I don't know the directory structure of your webspace, neither do i know your php version or config, nor do i know if the autoloader loads correctly. So please go and install it on a local machine first and check if everything runs fine. If it works locally, go and copy the whole project to your webspace. Come back if the problem still exists then.

**Comment by Eranio2012** [comment]
I have no local environment on my PC.
I have Download your gist and upload this on my webspace 
create the db file with my config

PHP version is 7

What is the correct installation guide?
That's what I asked above

This saved us time

**Comment by codemasher** [comment]
All necessary steps are explained. I can't help you if you refuse to go through the installation and test on a local machine. This is going nowhere.

**Comment by Eranio2012** [comment]
i say it again!
this is direct from gist and have no Installation 
Say me was i must make !!!

**Comment by codemasher** [comment]
If you were willing to accept help, you would have read the installation instructions and have followed them OR you would have used the linked gitter channel and realized that all necessary info is in there.
If you have no idea what you're actually doing, this repo isn't meant for you anyway. Stop wasting my time, please.
